# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a27c80226c539a6c2d398afabf01af862017bdc3e1f595c2988eac45455c49514602354e225672f0173838f4bdb6682bdd5424445e0d9b041164409f4f4ca7d

test:
  secret_key_base: b19a0fbe497c765f10f5204e3bb1367192488aa86a422e7efd3a8b6b67b22f1a8eb12151f29459f11f3df0e343a948f3742074f3877a52e75db223d67a346866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
